### PR TITLE
DC-430 Migrate Netflow Logic (Code) to new minion

### PR DESCRIPTION
**Pull request by FrancescoBuc86**
This PR takes Netflow Parser and Listener from OpenNMS classic and adds it to Minion NG into the _flows_ package
it solves the following tickets:

* DC-430: Migrate Netflow Logic (Code) to new minion
* DC-429: Wire Up (Osgi) flow code in new minion 
* DC-484: Make Flows in Minion NG functional

**=> The goal is to make it functional, not pretty**

There is follow up work to do but will be addressed in new Pull Request(s):
* DC-485: Clean up migrated code
* DC-431: Flow Handoff from Minion to Cloud

### CODE REVIEW

**Comment by FrancescoBuc86** [comment]
https://opennms.atlassian.net/browse/DC-430

**Comment by j-white** [comment]
What's expected to work in this PR? There's a lot of code to review here.

**Comment by patrick-schweizer** [comment]
> What's expected to work in this PR? There's a lot of code to review here.

This is a copy of OpenNMS Classic bits that we think we will need for the flow process in Minion NG.
The classes have been mostly left unchanged so far (@FrancescoBuc86 fixed some Sonar Bugs).

Next step (next PR) will be to make it functional (its actually listening for flows).

Originally I thought we would make these PRs against a feature branch. But I believe we decided we want to merge as soon as possible into develop?

@j-white does that work for you or would you and @geraldhumphries would prefer a different strategy?

**Comment by splatch** [comment]
Looking at structures - main part of it is JAXB generated code which we probably need to transform into protobuf definitions. Is there a plan for that?

**Review by patrick-schweizer — APPROVED** [review]
@FrancescoBuc86 showed me the working process:

1. sending UDP Packet
2. received by Minion
3. parsing
4. passing on to Async dispatcher

=> it looks like the code is functional and I think it can be merged. @geraldhumphries ok for you?

Next steps will be:
DC-485: Clean up migrated code
DC-431: Flow Handoff from Minion to Cloud

**Pull request merged**
