### PR TITLE
HS-292: Add latency / uptime metrics for default minion

### PR DESCRIPTION
**Pull request by mikewrosey**
## Description
Add latency / uptime metrics for current minion (hardcoded to default minion for now)
looks like additional be work will be needed before we can retrieve a list of minion metrics

## Jira link(s)
- https://issues.opennms.org/browse/HS-292

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

### CODE REVIEW

**Review by chinh-cle — APPROVED** [review]

**Comment by cgorantla** [comment]
@mikewrosey 
`query {
	listMinions {
		minions {
			id
			location
			label
			lastUpdated
		}
	}
}`

can be used to get list of minions and then use  `id` as instance label  and `location` as parameters  for this query

`query {metric(name: "minion_uptime_sec", labels: {location: "Default", instance:"minion-01"}) {status data {resultType result{metric value}}}} `

**Comment by mikewrosey** [comment]
> @mikewrosey `query { listMinions { minions { id location label lastUpdated } } }`
> 
> can be used to get list of minions and then use `id` as instance label and `location` as parameters for this query
> 
> `query {metric(name: "minion_uptime_sec", labels: {location: "Default", instance:"minion-01"}) {status data {resultType result{metric value}}}} `

@cgorantla I'm a bit hesitant to hook it up like that because if we're displaying 30 minions it would mean 30 separate requests. I thought it might be possible to make a resolver that handled lists of locations/instances and return all the metrics at once. What do you think?

**Comment by cgorantla** [comment]
> > @mikewrosey `query { listMinions { minions { id location label lastUpdated } } }`
> > can be used to get list of minions and then use `id` as instance label and `location` as parameters for this query
> > `query {metric(name: "minion_uptime_sec", labels: {location: "Default", instance:"minion-01"}) {status data {resultType result{metric value}}}} `
> 
> @cgorantla I'm a bit hesitant to hook it up like that because if we're displaying 30 minions it would mean 30 separate requests. I thought it might be possible to make a resolver that handled lists of locations/instances and return all the metrics at once. What do you think?

sure. I'm trying few things. Will update!

**Comment by mikewrosey** [comment]
Will merge this for now, to make use of some of the other changes in here. Will modify the metrics queries separately.

**Pull request merged**
