### PR TITLE
Features/use shared lib in minion

### PR DESCRIPTION
**Pull request by mfrazier63**
## Description
This shifts minion to use the new shared ipc module and also the new parent pom

## Jira link(s)
- https://issues.opennms.org/browse/HS-xx

## Checklist
* [ ] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [ ] Appropriate reviewer(s) have been selected.
* [ ] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

### CODE REVIEW

**Comment by splatch** [comment]
Looking at the list of commits it seems that this PR ships changes (or merges) which been in place since last week. Overall it breaks due to grpc contract update. The shared `ipc-grpc-contract` does not have `MinionHeader` any more. Instead it uses a renamed grpc structure called `Identity` - this is to open it for re-use in rpc or sink message envelopes.

Please check your branch with my changes I made on top of it: https://github.com/OpenNMS/horizon-stream/tree/features/grpc-features-cleanup.

**Comment by splatch** [comment]
I made a test drive of this PR and it compiles fine. Its good to go.

**Review by splatch — APPROVED** [review]

**Comment by mfrazier63** [comment]
retargeting

**Comment by mfrazier63** [comment]
closing

**Comment by mfrazier63** [comment]
Retargeting

**Pull request closed without merging**
