### PR TITLE
HS-188: Minion location should be Default

### PR DESCRIPTION
**Pull request by cgorantla**
## Description
Update minion location to `Default`

## Jira link(s)
- https://issues.opennms.org/browse/HS-188

## Checklist
* [x] Follows Horizon Stream's [development guidelines.](https://github.com/OpenNMS/horizon-stream/wiki/Development-Guidelines)
* [x] Appropriate reviewer(s) have been selected.
* [x] Jira issue(s) have been updated to "In Review".
* [ ] Includes [appropriate tests.](https://github.com/OpenNMS/horizon-stream/wiki/Test-Strategy)
* [ ] Documentation has been updated as necessary.

### CODE REVIEW

**Comment by cgorantla** [comment]
Response from the BFF:
```
{
  "data": {
    "listMinions": {
      "minions": [
        {
          "id": "minion-01",
          "location": "Default",
          "label": null,
          "lastUpdated": "2022-07-20T17:57:23.430Z"
        }
      ]
    }
  }
}
```

**Comment by cgorantla** [comment]
From logs:
```
[horizon-stream-core] 17:55:53.625 INFO  [sink-consumer-0] Received heartbeat for Minion with id: minion-01 at location: Default
[horizon-stream-core] 17:55:56.454 INFO  [minion-monitor-1] Minion RPC Monitor: executing check for minion: id=minion-01; location=Default
[horizon-stream-core] 17:55:56.576 INFO  [minion-monitor-1] ECHO RESPONSE: node-id=minion-01; node-location=Default; duration=116ms
[horizon-stream-core] 17:56:23.432 INFO  [sink-consumer-0] Received heartbeat for Minion with id: minion-01 at location: Default
```

**Review by yangli2014 — APPROVED** [review]
Looks good to me

**Comment by cgorantla** [comment]
will update tests in #165

**Pull request merged**
