### PR TITLE
HS-368: Remove all the 3rd party operators; bunch of cleanup

### PR DESCRIPTION
**Pull request by jkapponms**
## Description
1) removed all 3rd party operators, and thus OLM as well
2) added a per-instance Kafka deployment managed by our operator
3) cleaned up a bunch of stuff hanging around

## Jira link(s)
- https://issues.opennms.org/browse/HS-368

### CODE REVIEW

**Comment by jaymberry** [comment]
Why are you getting rid of charts/opennms-operator/templates/cert/* and charts/opennms-operator/templates/custom-errors/nginx-errors-deployment.yaml?

**Comment by jkapponms** [comment]
> Why are you getting rid of charts/opennms-operator/templates/cert/* and charts/opennms-operator/templates/custom-errors/nginx-errors-deployment.yaml?

Files in `templates/cert/*` were both cert-manager CRDs

And nothing's using the custom errors backend.

**Comment by jaymberry** [comment]
Ok, we will need charts/opennms-operator/templates/custom-errors/nginx-errors-deployment.yaml, will want to plug them in. Can you keep them there until we get to that. Maybe create a ticket and assign to me, low priority.

**Comment by jkapponms** [comment]
Sure thing.

**Review by jaymberry — APPROVED** [review]

**Review by geraldhumphries — APPROVED** [review]

**Pull request merged**
